spring:
  devtools:
    livereload:
      enabled: true  #禁用livereload服务器
    remote:
      restart:
        enabled: false
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
  mvc:
    favicon:
      enabled: false #禁用浏览器图标
management:
  endpoints:
    web:
      exposure:
        include: "*"
debug: true #调试模式，将会看到更多的日志信息。默认关闭