spring:
  devtools:
    livereload:
      enabled: false  #禁用livereload服务器
      port: 35729 #注意多个端口冲突
    remote:
      restart:
        enabled: false
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
  mvc:
    favicon:
      enabled: false #禁用浏览器图标
management:
  endpoints:
    web:
      exposure:
        include: "*"
